# Generated by Django 3.0.7 on 2020-07-22 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_weight', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 7, 22))),
                ('diet_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.Product')),
                ('profile_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
