# Generated by Django 3.0.7 on 2020-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories_plan',
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet_type',
            field=models.CharField(choices=[('1', 'Vegan'), ('2', 'Vegeterian'), ('3', 'Paleo'), ('4', 'Keto'), ('5', 'None')], default='5', max_length=2),
        ),
    ]
