# Generated by Django 3.0.7 on 2020-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200722_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product_weight',
            field=models.IntegerField(default=100),
        ),
    ]
