# Generated by Django 3.0.7 on 2020-08-11 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200806_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 11)),
        ),
    ]
