# Generated by Django 3.0.7 on 2020-07-23 12:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200722_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 12, 51, 29, 846102, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='User_Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='Account.Diet')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
