# Generated by Django 3.0.7 on 2020-07-24 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20200723_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 24)),
        ),
    ]
