# Generated by Django 3.0.7 on 2020-08-01 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20200724_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 1)),
        ),
    ]
