# Generated by Django 3.0.7 on 2020-08-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20200801_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 3)),
        ),
    ]
