# Generated by Django 3.0.7 on 2020-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredinet_based',
            field=models.BooleanField(default=False),
        ),
    ]
