# Generated by Django 3.0.7 on 2020-08-06 13:48

import Food.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(validators=[Food.validators.macro_quantity_validator]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(validators=[Food.validators.macro_quantity_validator]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(validators=[Food.validators.macro_quantity_validator]),
        ),
    ]
