# Generated by Django 3.0.7 on 2020-07-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_product_ingredinet_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
