# Generated by Django 3.0.7 on 2020-08-13 15:47

import Food.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20200813_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, validators=[Food.validators.price_validator]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_per_portion',
            field=models.IntegerField(blank=True, validators=[Food.validators.weight_validaotr]),
        ),
    ]
